/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VCSBT } from "./VCSBT";
export * as factories from "./factories";
export { VCSBT__factory } from "./factories/VCSBT__factory";
